### ISSUE TITLE
CI workflow doesn't test toolchain targets correctly

### ISSUE THREAD

**Issue by Mrmaxmeier** [RazrFalcon/memmap2-rs#20]
This build step doesn't work as expected because rustup does not manage rustc's default target:
```yaml
- name: Install toolchain
  uses: actions-rs/toolchain@v1
  with:
    toolchain: stable
    profile: minimal
    target: ${{ matrix.target }}
    override: true

- name: Run tests
  run: cargo test
```

The tests fail when the target is set explicitly:
```diff
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index 380f1d0..b3e4c16 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -49,7 +49,7 @@ jobs:
         override: true
 
     - name: Run tests
-      run: cargo test
+      run: cargo test --target ${{ matrix.target }}
 
   test-macos-catalina:
     runs-on: macos-10.15
@@ -82,7 +82,7 @@ jobs:
         override: true
 
     - name: Run tests
-      run: cargo test
+      run: cargo test --target ${{ matrix.target }}
```

`i686-unknown-linux-musl` seems to run into a 32-bit truncation issue:
```
---- test::map_offset stdout ----
thread 'test::map_offset' panicked at 'attempt to subtract with overflow', src/lib.rs:179:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
and `i686-unknown-linux-gnu` fails during linking probably because 32-bit glibc isn't installed or something.

Here's a sample run (not sure if it'll survive force-pushes): https://github.com/Mrmaxmeier/memmap2-rs/runs/3251483567 (xref #21)
