### ISSUE TITLE
Merging changes with memmapix

### ISSUE THREAD

**Issue by nyurik** [RazrFalcon/memmap2-rs#92]
Hi, I noticed that @al8n has made some changes in their fork https://github.com/al8n/memmapix, while this repo has also done some diverging work.  This repo clearly has far more downloads/community following, so I wonder if it would be possible to merge some/all of the memmapix changes into this repo, or what's your future plans for this repo?

Both efforts would clearly benefit the community, and highly appreciated, thank you all!

P.S. The `memmapix` repo doesn't have issues tab for some reason, so I couldn't ask for it there.

**Comment by adamreichold** [comment]
I think the main change there is unconditionally swapping out `libc` for `rustix` to support Unix-like platforms without going through the system C library which we discussed here and decided against for now, c.f. #85.

I guess we could add a feature for swapping out those two system call layers, e.g.

```toml
[dependencies]
libc = { version = "0.2", optional = true }
rustix = { version = "0.35", features = ["fs", "mm", "param"], optional = true }

[features]
default = ["libc"]
```

but I still have no heard a good motivation as for why the additional complexity for maintaining both implementations is required.
